name: Extract Text from Documents

on:
  push:
    paths:
      - 'interrogation-materials/**'
      - 'scripts/extract_text.py'
      - '.github/workflows/extract_text.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r scripts/requirements.txt
      - name: Extract text from documents
        run: python scripts/extract_text.py
      - name: Commit and push extracted text
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add extracted/
          git commit -m "Automated text extraction from interrogation-materials" || echo "No changes to commit"
          git push
